Criando automacao

diff --git a/.github/workflows/deploy-lambda.yml b/.github/workflows/deploy-lambda.yml
--- a/.github/workflows/deploy-lambda.yml
+++ b/.github/workflows/deploy-lambda.yml
@@ -22,11 +22,16 @@ jobs:
       - name: Build the .jar file with Maven
         run: mvn clean package
 
-      - name: Install AWS CLI
+      - name: Verify AWS CLI Installation
         run: |
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install
+          if ! aws --version; then
+            echo "AWS CLI not found, installing..."
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+          else
+            echo "AWS CLI already installed."
+          fi
 
       - name: Update Lambda Function
         env:
@@ -36,4 +41,4 @@ jobs:
         run: |
           aws lambda update-function-code \
             --function-name AutenticacaoCPFHandler \
-            --zip-file fileb://target/lambda-aut-cpf-1.0-SNAPSHOT.jar
+            --zip-file fileb://target/lambda-cpf.jar
